title: John Fitzgerald
description: AI, Games, and Sandbox Projects
theme: jekyll-theme-architect

# This tells Jekyll to look for posts
collections:
  posts:
    output: true
    
# Custom footer or variables
kofi_id: johndfitzgerald
